### ISSUE TITLE
published port

### ISSUE THREAD

**Issue by adastreamer** [dokkur/swanager#4]
Предложение:

1. запретить принудительно указывать, какой порт должен быть открыт снаружи
2. в эндпоинт /services в объектах Service брать фактический экспоуженный published_ports Docker-ом (сейчас если при создании передать туда 0 в качестве External Port, swarm сам выберет внешний порт, но его потом никак получить нельзя)

**Comment by da4nik** [comment]
Да, там ещё проверку надо впилить, что такой порт уже запаблишен. 
`экспоуженный published_ports` определись с терминологией, смешал 2 разных понятия
